### PR TITLE
Added min and max options for RGBA and hex number generator

### PR DESCRIPTION
**Pull request by caimen**
Added min and max options for RGBA and hex number generator

### CODE REVIEW

**Comment by caimen** [comment]
This pull request is to solve Issue #289.  I'm not sure what this last test build check is all about though.

**Comment by caimen** [comment]
So I get this is failing because the Node 6 test was never fully finished per pull request #274 , otherwise we should be good here.

**Comment by caimen** [comment]
@victorquinn I believe everything is correct here now.  If there is something specific I need to get the Travis build to work correctly let me know.

**Comment by victorquinn** [comment]
It's been on my todo to iron out the issues with Travis on Node 6.x so no worries, thanks for the addition!

**Pull request merged**
