### PR TITLE
Add prime generator and is_prime helper function

### PR DESCRIPTION
**Pull request by inad9300**
Hopefully this is working and you find it interesting enough :slightly_smiling_face: Unfortunately, I haven't been able to test it - when running `npm test` (after `npm install`) I get:

```
> chance@1.0.16 test /home/daniel/Code/chancejs
> gulp travis

gulp[11793]: ../src/node_contextify.cc:628:static void node::contextify::ContextifyScript::New(const v8::FunctionCallbackInfo<v8::Value>&): As
sertion `args[1]->IsString()' failed.
 1: node::Abort() [gulp]
 2: 0x876c55 [gulp]
 3: node::contextify::ContextifyScript::New(v8::FunctionCallbackInfo<v8::Value> const&) [gulp]
 4: v8::internal::FunctionCallbackArguments::Call(v8::internal::CallHandlerInfo*) [gulp]
 5: 0xacd2df [gulp]
 6: v8::internal::Builtin_HandleApiCall(int, v8::internal::Object**, v8::internal::Isolate*) [gulp]
 7: 0x14e0e7b0427d
Aborted (core dumped)
npm ERR! Test failed.  See above for more details.
```

This is, using Node v10.1.0 and npm 6.1.0 on elementary OS.

### CODE REVIEW

**Comment by victorquinn** [comment]
Love this addition though it seems to blow up on the tests

**Comment by victorquinn** [comment]
Not a clue why it won’t run locally, but it’s failing on Travis because it’s not passing the linting. 

We enforce === always in Chance and your code has == in the is_prime function.

**Comment by inad9300** [comment]
Thanks for pointing it out, it escaped me. I'll fix it soon ;)

**Comment by inad9300** [comment]
The tests were failing because Gulp 3 and Node.js 10 don't play well together. I have upgraded the Gulp version in the `package.json` to 4, and adapted the `gulpfile.js` accordingly, since there were a few breaking changes.

**Comment by victorquinn** [comment]
Ahh excellent, thanks @inad9300 sorry for the troubles but thanks for keeping Chance up to date!

**Pull request merged**
