### PR TITLE
Implements Issue #307.

### PR DESCRIPTION
**Pull request by WriteCodeEveryday**
Adds two calls - locale() and locales() under the “Web section”.

Tests for locale() in both region and without region have been created.

### CODE REVIEW

**Comment by ricardogama** [comment]
This seems a must have, @victorquinn any way you can review this?

**Comment by victorquinn** [comment]
Looks good, sorry it took me a bit to review!

**Comment by ricardogama** [comment]
Thanks @victorquinn! Any chance of releasing this?

**Comment by victorquinn** [comment]
Yup, it's now live on npm as 1.0.7!

**Comment by ricardogama** [comment]
Really cool, don't forget to update the docs. Cheers!

**Pull request merged**
