### PR TITLE
CNPJ generator added

### PR DESCRIPTION
**Pull request by eurafa**
Hello. 
I implemented another brazillian number generator: **CNPJ**.
It's like a **CPF**, but for companies instead citizens.

@victorquinn:
- How can I contribute updating documentation?
- Who should to update the minified javascript file?

Thank you

### CODE REVIEW

**Comment by leesei** [comment]
Did you pass test locally? Travis timed out.

You can update docs in [`gh-pages`](https://github.com/victorquinn/chancejs/tree/gh-pages) branch.

**Comment by eurafa** [comment]
Hi, @leesei. How're you? I was waiting some message. Thank you.
I'm think my test has passed. I didn't know why Travis CI build gaves me a timeout.
I did that some months ago, so I was not sure then I did a new simple commit to retrigger Travis CI build.
But bow the build has passed successfully!!
I commited the documentation for CNPJ.
Please can you check it also?

**Comment by leesei** [comment]
I'm merely a pass-by commentator :grinning:.
Travis as a free service did not provide 100% accurate result, its better to state you passed the test locally to let @victorquinn know it is safe to merge.

**Comment by victorquinn** [comment]
Nice change, thanks for the tests!

Sorry this got lost for awhile, I was waiting on the tests which I re-ran and they passed so it's all good

**Pull request merged**
