### PR TITLE
Added generators for music: notes, chords, tempos

### PR DESCRIPTION
**Pull request by ryanmonro**
Added note(), midi_note(), chord(), chord_quality(), tempo()
I'm new to this, let me know if there's any problems. Hopefully this will come in handy - the first time I saw Chance.js in action was for something music-related so I was surprised to see no music functions in there.
Also, I'd be happy to write the documentation for these.

### CODE REVIEW

**Comment by mattgrande** [comment]
Neat! I think it'd be nice if you used the actual flat/sharp symbols (♭/♯).

**Comment by ryanmonro** [comment]
@mattgrande great idea! I'll put those in now. Thanks.

**Comment by victorquinn** [comment]
Love this, awesome addition @ryanmonro !

And I’m also a fan of the true flat and sharp symbols. 

Only thing I’m not sure about is the selection to group notes by Flat and Sharp. Seems by default I’d want any single note at random which may be Flat, Sharp, or Normal (unmodified with no flat or sharp). 

Then if I were to specify Flat I’d get a random Flat note (not a Flat or a Normal note) and if I specify Sharp I get a random Sharp note (not a Sharp or Normal note) or Normal (or whatever the proper music term is here).

**Comment by ryanmonro** [comment]
Ah, currently it will generate any random note, including the flats and sharps. The key option dictates whether the flats and sharps will be written as flat or sharp. ie if options contained {key: 'flat} it would give you a G♭, whereas that note would be an F# if the key option was 'sharp'.

**Comment by victorquinn** [comment]
Yes, I understand how it currently works, my comment was that, as written, it is impossible to guarantee that I get a note that is actually Flat, Sharp, or "Normal." 

This seems bad to me. 

I can foresee use cases where someone would want to ensure they get a certain type of note and it is not possible as written.

`tempo()`, `midi_note()` and `chord()` look great but I'd like some solution here for `note()` that's a bit cleaner before I merge it in.

**Comment by ryanmonro** [comment]
Okay, I'll add some more options. The normal notes are currently in both arrays too, that seems a bit redundant.

**Comment by victorquinn** [comment]
Looking great, thank you @ryanmonro for making the requested changes :)

**Comment by ryanmonro** [comment]
Thanks for merging @victorquinn, this is my first open source code contribution, it's very exciting

**Comment by victorquinn** [comment]
No problem, this is an awesome addition that I never even considered! Hopefully this process wasn’t too painful and this can be the first of many :)

**Pull request merged**
