### PR TITLE
Career enhancements.

### PR DESCRIPTION
**Pull request by WriteCodeEveryday**
- Fixes the “profession” method and adds tests for it.

- Adds rank option for “profession”

- Add company list and method for retrieving a random company.

Please execute tests before merging in order to verify work (npm install does not complete on Mac OS X, hangs with “Copying extracted folder /var/folders/6z/bybrj4pn4q70r9ddxfzhf3s80000gn/T/phantomjs/phantomjs-1.9.8-macosx.zip-extract-1492023755933/phantomjs-1.9.8-macosx -> /Users/<USERNAME_HERE>/chancejs/node_modules/grunt-js-test/node_modules/phantomjs/lib/phantom”)

### CODE REVIEW

**Comment by victorquinn** [comment]
Looks great, thanks for your addition!

Sorry Travis is being finicky on Node 4.x, that's a known issue, you're all green elsewhere!

**Comment by WriteCodeEveryday** [comment]
Off-topic, but would it be alright if I brought this in from my own repo? 

http://writecodeeveryday.github.io/projects/pdf417js/

It uses chance.js to generate a PDF417 and encode it into a QR code. I would just spit out the string representation instead.

I'm not sure if it would be an inception to pull a project made with chance.js into chance.js but anyone testing any sort of QR scanning for PDF417 would probably love something that generates a valid PDF417 format.

I'd probably toss in magnetic stripe generation for licenses as well (I based the whole thing off the ANSI Florida Standards, but those are used through the entire US)

**Comment by victorquinn** [comment]
@WriteCodeEveryday I think that's certainly cool but probably doesn't belong in the Chance core.

I'm happy to create a new repo for you on the Chance org though and you can make it a mixin like [some others](https://github.com/chancejs) here that didn't seem core-worthy.

**Comment by WriteCodeEveryday** [comment]
@victorquinn I'm okay with either one, I figured a driver's license and it's "accompanying info" would fall under the "Person" model, that's all,

**Pull request merged**
