### PR TITLE
Add random emoji generation.

### PR DESCRIPTION
**Pull request by dylanhamersztein**

### CODE REVIEW

**Review by JohnAllenTech — COMMENTED** [review]
This is awesome! Id love to see this merged in

**Review by victorquinn — APPROVED** [review]
Looks great! Will cut a new build with this and push to npm shortly

**Comment by JohnAllenTech** [comment]
Hmmm looks like tests are all failing. Are you open to a PR to resolve this @victorquinn ?

**Comment by victorquinn** [comment]
I see that 😢 yes would love a PR that resolves it -- not sure what has gone awry there

**Comment by JohnAllenTech** [comment]
> I see that 😢 yes would love a PR that resolves it -- not sure what has gone awry there

I have opened #600 as a first step to fixing this. Please review when you get a chance. 🚀

**Comment by JohnAllenTech** [comment]
@dylanhamersztein you may need to sync this with master again so the new test node versions are pulled in. Then this will possibly be able to be merged

**Comment by dylanhamersztein** [comment]
hey guys! thanks so much for all your help 😄 i've just synced this branch with master fixed the tests to account for what @victorquinn found on #601

**Comment by dylanhamersztein** [comment]
Hi @victorquinn  😄 sorry to bother but would you mind taking another look at this please? I'd love to be able to say I contributed to this project!

**Comment by victorquinn** [comment]
Not a bother, appreciate the ping and the work @dylanhamersztein

**Comment by victorquinn** [comment]
fyi this is live on npm as 1.1.12 😄

**Pull request merged**
