### PR TITLE
Travis should test on Node 6

### PR DESCRIPTION
**Pull request by EvanHahn**
Node 6 is the latest version. It might be helpful to run Travis tests on the latest version.

It's pretty similar to Node 4, so I understand if this PR is rejected.

### CODE REVIEW

**Comment by victorquinn** [comment]
This is great, happy to accept it, though I'm not sure if it'll pass as is

**Comment by EvanHahn** [comment]
I'll try to fix it. Do you want me to squash commits?

**Comment by victorquinn** [comment]
> Do you want me to squash commits?

I leave it up to you, not a big deal either way. Thanks!

**Comment by EvanHahn** [comment]
Ugh, having an issue installing Phantom (it's hanging copying a file). I'll see if I can't sort this out.

**Comment by victorquinn** [comment]
This is fixed as of my recent revamp of the testing infrastructure!

**Pull request closed without merging**
